heat_template_version: queens
description: >
  Software Config to drive os-net-config to configure multiple interfaces for the Compute role.
parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage_mgmt network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal_api network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  ManagementIpSubnet:
    default: ''
    description: IP address/subnet on the management network
    type: string
  BondInterfaceOvsOptions:
    default: 'bond_mode=active-backup'
    description: The ovs_options string for the bond interface. Set things like
                 lacp=active and/or bond_mode=balance-slb using this option.
    type: string
  BondInterfaceLinuxOptions:
    default: 'mode=active-backup miimon=100'
    description: The Linux bond configuration
    type: string
  StorageNetworkVlanID:
    default: 30
    description: Vlan ID for the storage network traffic.
    type: number
  StorageMgmtNetworkVlanID:
    default: 40
    description: Vlan ID for the storage_mgmt network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 20
    description: Vlan ID for the internal_api network traffic.
    type: number
  TenantNetworkVlanID:
    default: 50
    description: Vlan ID for the tenant network traffic.
    type: number
  ExternalNetworkVlanID:
    default: 10
    description: Vlan ID for the external network traffic.
    type: number
  ManagementNetworkVlanID:
    default: 60
    description: Vlan ID for the management network traffic.
    type: number
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  ControlPlaneDefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ExternalInterfaceDefaultRoute:
    description: default route for the external network
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: /usr/share/openstack-tripleo-heat-templates/network/scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:
              - type: linux_bond
                name: bond0
                mtu: 9000
                bonding_options: {get_param: BondInterfaceLinuxOptions}
                use_dhcp: false
                dns_servers: {get_param: DnsServers}
                addresses:
                - ip_netmask:
                    list_join:
                    - /
                    - - get_param: ControlPlaneIp
                      - get_param: ControlPlaneSubnetCidr
                routes:
                - ip_netmask: 169.254.169.254/32
                  next_hop: {get_param: EC2MetadataIp}
                - default: true
                  next_hop: {get_param: ControlPlaneDefaultRoute}
                members:
                - type: interface
                  name: nic1
                  mtu: 9000
                  primary: true
                - type: interface
                  name: nic2
                  mtu: 9000
                - type: interface
                  name: nic3
                  mtu: 9000
                - type: interface
                  name: nic4
                  mtu: 9000

              - type: vlan
                device: bond0
                mtu: 9000
                vlan_id: {get_param: InternalApiNetworkVlanID}
                addresses:
                - ip_netmask: {get_param: InternalApiIpSubnet}

              - type: vlan
                vlan_id: {get_param: StorageNetworkVlanID}
                device: bond0
                mtu: 9000
                addresses:
                - ip_netmask: {get_param: StorageIpSubnet}

              - type: ovs_user_bridge
                name: br-link0
                mtu: 9216
                use_dhcp: false
                ovs_extra:
                - str_replace:
                    template: set port $DEVICE tag=_VLAN_TAG_
                    params:
                      _VLAN_TAG_: {get_param: TenantNetworkVlanID}
                - set interface $DEVICE mtu_request=$MTU
                addresses:
                - ip_netmask: {get_param: TenantIpSubnet}
                members:
                - type: ovs_dpdk_bond
                  name: ovsbond0
                  ovs_options: {get_param: BondInterfaceOvsOptions}
                  mtu: 9216
                  ovs_extra:
                  - set interface dpdk0 options:n_rxq=2
                  - set interface dpdk0 other_config:pmd-rxq-affinity="0:2,1:4"
                  - set interface dpdk1 options:n_rxq=2
                  - set interface dpdk1 other_config:pmd-rxq-affinity="0:4,1:2"
                  # DPDK DRIVERS
                  # https://access.redhat.com/articles/3538141
                  # Driver "vfio-pci" for the following NIC Families:
                  #  - Intel:
                  #    - Niantic: 82598, 82599, X520, X540, X550
                  #    - Fortville: X710, XL710, XXV710, X722
                  #  - Broadcom: NetXtreme-C, NetXtreme-E, StrataGX, 573xxm 574xx
                  #  - Marvell / Cavium: FastLinQ QL4xxxx
                  #  - Netronome: Agilio CX Series
                  #  - Cisco: VIC 1340, VIC 1400
                  # Driver "mlx5_core" to be used for:
                  #  - Mellanox: ConnectX-4, ConnectX-4 Lx, ConnectX-5, ConnectX-6
                  # Driver "mlx4_core" to be used for:
                  #  - Mellanox: ConnectX-3, ConnectX-3 Pro (RHEL7-only)
                  members:
                  - type: ovs_dpdk_port
                    name: dpdk0
                    driver: vfio-pci
                    mtu: 9216
                    members:
                    - type: interface
                      name: nic5
                  - type: ovs_dpdk_port
                    name: dpdk1
                    driver: vfio-pci
                    mtu: 9216
                    members:
                    - type: interface
                      name: nic6

              - type: ovs_user_bridge
                name: br-link1
                mtu: 9216
                use_dhcp: false
                members:
                - type: ovs_dpdk_bond
                  name: ovsbond1
                  ovs_options: {get_param: BondInterfaceOvsOptions}
                  mtu: 9216
                  ovs_extra:
                  - set interface dpdk2 options:n_rxq=2
                  - set interface dpdk2 other_config:pmd-rxq-affinity="0:3,1:5"
                  - set interface dpdk3 options:n_rxq=2
                  - set interface dpdk3 other_config:pmd-rxq-affinity="0:5,1:3"
                  members:
                  - type: ovs_dpdk_port
                    name: dpdk2
                    driver: vfio-pci
                    mtu: 9216
                    members:
                    - type: interface
                      name: nic7
                  - type: ovs_dpdk_port
                    name: dpdk3
                    driver: vfio-pci
                    mtu: 9216
                    members:
                    - type: interface
                      name: nic8

outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value:
      get_resource: OsNetConfigImpl
